version: '3.8'
services:
 postgres_db:
  image: postgres:latest
  container_name: PostgresCont 
  restart: always
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=pas
   - POSTGRES_DB_PORT=5432
   - POSTGRES_DB_HOST=localhost
  ports:
   - '5432:5432'
  volumes:
   - postgres_db:/var/lib/postgresql/data
volumes:
 postgres_db:
  driver: local
networks:
 postgres_db_network:
  driver: bridge   